apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo
spec:
  type: ClusterIP
  selector:
    name: mysql
    app: demo
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
